# Generated by Django 6.0 on 2025-12-10 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stuscore', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stuscore',
            old_name='age',
            new_name='eng',
        ),
        migrations.RemoveField(
            model_name='stuscore',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='stuscore',
            name='grade',
        ),
        migrations.AddField(
            model_name='stuscore',
            name='avg',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='stuscore',
            name='kor',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stuscore',
            name='math',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stuscore',
            name='total',
            field=models.IntegerField(default=0),
        ),
    ]
